# Generated by Django 4.2.4 on 2023-08-28 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_chart"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("chart_type", models.CharField(max_length=100)),
                ("chart_image", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="chart",
            name="chart_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chart_chart_type",
                to="registry.charttype",
            ),
        ),
    ]
