# Generated by Django 4.2.4 on 2023-09-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_dashboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charttype',
            name='chart_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
