# Generated by Django 4.2.4 on 2023-09-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0005_alter_charttype_chart_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chart",
            name="chart_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chart_chart_type",
                to="registry.charttype",
            ),
        ),
    ]
