# Generated by Django 4.2.4 on 2023-09-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0006_alter_chart_chart_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charttype",
            name="chart_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
