# Generated by Django 4.2.4 on 2023-09-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0008_chart_chart_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="chart",
            name="chart_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chart",
            name="chart_width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
